#!/usr/bin/python
# -*- coding: utf-8 -*-

# Caution! I am not responsible for using these samples. Use at your own risk
# Google, Inc. is the copyright holder of samples downloaded with this tool.

# Generated automatically by imgw_podest.py. Feel free to modify it SLIGHTLY.

LANGUAGE = 'pl'

START_MARKER = 'ę. '
END_MARKER = ' k'

CUT_START = 0.9
CUT_END=0.7

download_list = [ 
    ['rzeka', 'rzeka'],
    ['wodowskaz', 'wodowskaz'],
    ['przekroczenia stanów alarmowych', 'przekroczenia_stanow_alarmowych'],
    ['komunikat hydrologiczny imgw', 'komunikat_hydrologiczny_imgw'],
    ['przekroczenia stanów ostrzegawczych', 'przekroczenia_stanow_ostrzegawczych'],
    ['Gniechowice', 'gniechowice'],
    ['Kamienica', 'kamienica'],
    ['Łazany', 'l_azany'],
    ['Jugowice', 'jugowice'],
    ['Gliwice-Łabędy', 'gliwice_l_abe_dy'],
    ['Bojanów', 'bojano_w'],
    ['Prudnik', 'prudnik'],
    ['Szprotawa', 'szprotawa'],
    ['Zborowice', 'zborowice'],
    ['Opole - Groszowice', 'opole___groszowice'],
    ['Karłowice', 'karl_owice'],
    ['Międzylesie', 'mie_dzylesie'],
    ['Krapkowice', 'krapkowice'],
    ['Odra', 'odra'],
    ['Kamienna Góra', 'kamienna_go_ra'],
    ['Iłowa', 'il_owa'],
    ['Pełcznica', 'pel_cznica'],
    ['Opawa', 'opawa'],
    ['Jarnołtów', 'jarnol_to_w'],
    ['Sosnówka', 'sosno_wka'],
    ['Zbytowa', 'zbytowa'],
    ['Cigacice', 'cigacice'],
    ['Orla', 'orla'],
    ['Rzeszotary', 'rzeszotary'],
    ['Łąki', 'l_a_ki'],
    ['Brzeg Dolny', 'brzeg_dolny'],
    ['Krasków', 'krasko_w'],
    ['Bystrzyca Łomnicka', 'bystrzyca_l_omnicka'],
    ['Gliwice', 'gliwice'],
    ['Łaziska', 'l_aziska'],
    ['Turawa', 'turawa'],
    ['Kanclerzowice', 'kanclerzowice'],
    ['Kowary', 'kowary'],
    ['Cieszyn', 'cieszyn'],
    ['Dąbrowa Bolesławiecka', 'da_browa_bolesl_awiecka'],
    ['Dzierżoniów', 'dzierz_onio_w'],
    ['Kaczawa', 'kaczawa'],
    ['Jedlica', 'jedlica'],
    ['Kopice', 'kopice'],
    ['Widawa', 'widawa'],
    ['Oława', 'ol_awa'],
    ['Pyskowice Dzierżno', 'pyskowice_dzierz_no'],
    ['Ścinawa', 's_cinawa'],
    ['Nysa Kłodzka', 'nysa_kl_odzka'],
    ['Gotartowice', 'gotartowice'],
    ['Osetno', 'osetno'],
    ['Koźle', 'kox_le'],
    ['Szalejów Dolny', 'szalejo_w_dolny'],
    ['Trestno', 'trestno'],
    ['Czarny Potok', 'czarny_potok'],
    ['Ścinawa Niemodlińska', 's_cinawa_niemodlin_ska'],
    ['Strzegomka', 'strzegomka'],
    ['Klikawa', 'klikawa'],
    ['Jelenia Góra', 'jelenia_go_ra'],
    ['Ujście Nysy Kłodzkiej', 'ujs_cie_nysy_kl_odzkiej'],
    ['Mirsk', 'mirsk'],
    ['Lądek Zdrój', 'la_dek_zdro_j'],
    ['Branice', 'branice'],
    ['Krupski Młyn', 'krupski_ml_yn'],
    ['Bystrzyca', 'bystrzyca'],
    ['Żelazno', 'z_elazno'],
    ['Wilkanów', 'wilkano_w'],
    ['Kudowa Zdrój - Zakrze', 'kudowa_zdro_j___zakrze'],
    ['Leśna', 'les_na'],
    ['Czarna Woda', 'czarna_woda'],
    ['Bogdaszowice', 'bogdaszowice'],
    ['Biała Lądecka', 'bial_a_la_decka'],
    ['Błażkowa', 'bl_az_kowa'],
    ['Podgórzyn', 'podgo_rzyn'],
    ['Barycz', 'barycz'],
    ['Czerwonka', 'czerwonka'],
    ['Czerna Mała', 'czerna_mal_a'],
    ['Olza', 'olza'],
    ['Drama', 'drama'],
    ['Piława', 'pil_awa'],
    ['Malczyce', 'malczyce'],
    ['Rzymówka', 'rzymo_wka'],
    ['Bardo', 'bardo'],
    ['Barcinek', 'barcinek'],
    ['Lubachów', 'lubacho_w'],
    ['Czerna Wielka', 'czerna_wielka'],
    ['Łozy', 'l_ozy'],
    ['Bystrzyca Kłodzka', 'bystrzyca_kl_odzka'],
    ['Stary Raduszec', 'stary_raduszec'],
    ['Prochowice', 'prochowice'],
    ['Tłumaczów', 'tl_umaczo_w'],
    ['Lenartowice', 'lenartowice'],
    ['Mietków', 'mietko_w'],
    ['Odolanów', 'odolano_w'],
    ['Ślęza', 's_le_za'],
    ['Młynówka', 'ml_yno_wka'],
    ['Rów Polski', 'ro_w_polski'],
    ['Świebodzice', 's_wiebodzice'],
    ['Podgórna', 'podgo_rna'],
    ['Bukowna', 'bukowna'],
    ['Kłodzko', 'kl_odzko'],
    ['Sąsiecznica', 'sa_siecznica'],
    ['Gorzuchów', 'gorzucho_w'],
    ['Jakuszyce', 'jakuszyce'],
    ['Żagań', 'z_agan_'],
    ['Ruda', 'ruda'],
    ['Chojnów', 'chojno_w'],
    ['Nysa Szalona', 'nysa_szalona'],
    ['Nowogród Bobrzański', 'nowogro_d_bobrzan_ski'],
    ['Kuroch', 'kuroch'],
    ['Piechowice', 'piechowice'],
    ['Głogów', 'gl_ogo_w'],
    ['Biała Nyska', 'bial_a_nyska'],
    ['Kwisa', 'kwisa'],
    ['Bóbr ', 'bo_br_'],
    ['Ścinawka', 's_cinawka'],
    ['Kamienna', 'kamienna'],
    ['Bogdaj', 'bogdaj'],
    ['Korzeńsko', 'korzen_sko'],
    ['Bierawka', 'bierawka'],
    ['Staniszcze Wielkie', 'staniszcze_wielkie'],
    ['Rybnik Stodoły', 'rybnik_stodol_y'],
    ['Dobroszów Wielki', 'dobroszo_w_wielki'],
    ['Biała Głuchołaska', 'bial_a_gl_uchol_aska'],
    ['Skora', 'skora'],
    ['Namyslów', 'namyslo_w'],
    ['Stobrawa', 'stobrawa'],
    ['Winnica', 'winnica'],
    ['Głuchołazy', 'gl_uchol_azy'],
    ['Jawor', 'jawor'],
    ['Kłodnica', 'kl_odnica'],
    ['Niemodlin', 'niemodlin'],
    ['Kamieniec Ząbkowicki', 'kamieniec_za_bkowicki'],
    ['Pyskowice', 'pyskowice'],
    ['Krzyżanowice', 'krzyz_anowice'],
    ['Świerzawa', 's_wierzawa'],
    ['Łomnica', 'l_omnica'],
    ['Piątnica', 'pia_tnica'],
    ['Nysa', 'nysa'],
    ['Gryfów Śląski', 'gryfo_w_s_la_ski'],
    ['Borów', 'boro_w'],
    ['Skorogoszcz', 'skorogoszcz'],
    ['Mała Panew', 'mal_a_panew'],
    ['Bystrzyca Dusznicka', 'bystrzyca_dusznicka'],
    ['Grabówka', 'grabo_wka'],
    ['Chałupki', 'chal_upki'],
    ['Nowogrodziec', 'nowogrodziec'],
    ['Chwaliszów', 'chwaliszo_w'],
    ['Budzówka', 'budzo_wka'],
    ['Wilczka', 'wilczka'],
    ['Polska Woda', 'polska_woda'],
    ['Bukówka', 'buko_wka'],
    ['Racławice Śląskie', 'racl_awice_s_la_skie'],
    ['Biała', 'bial_a'],
    ['Brzeg', 'brzeg'],
    ['Nowa Sól', 'nowa_so_l'],
    ['Osobłoga', 'osobl_oga'],
    ['Bóbr', 'bo_br'],
    ['Ozimek', 'ozimek'],
    ['Dunino', 'dunino'],
    ['Białobrzezie', 'bial_obrzezie'],
    ['Istebna', 'istebna'],
    ['Zagrodno', 'zagrodno'],
    ['Rydzyna', 'rydzyna'],
    ['Pilchowice', 'pilchowice'],
    ['Ruda Kozielska', 'ruda_kozielska'],
    ['Psina', 'psina'],
    ['Nietków', 'nietko_w'],
    ['Ślęża', 's_le_z_a'],
    ['Mościsko', 'mos_cisko'],
    ['Dobra', 'dobra'],
    ['Wojanów', 'wojano_w'],
    ['Racibórz Miedonia', 'racibo_rz_miedonia'],
]

